version: "2"
services:
  api:
    build: .
    ports:
      - "4455:4567"
    command: "ruby languages.rb"
    environment:
      - DB_HOSTNAME=db:27017
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul
  db:
    image: mongo
  consul:
    image: consul
